title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://dutu.github.io/run-on-tails

aux_links:
  Contribute! Source on GitHub: https://github.com/dutu/run-on-tails/
