title: Run-on-Tails
description: A Guide on how to run various applications on Tails OS
theme: just-the-docs
color_scheme: dark
markdown: kramdown

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

url: https://dutu.github.io/run-on-tails

nav_external_links_new_tab: true

aux_links:
  Issues / Knowledge Base: https://github.com/dutu/run-on-tails/issues
  Contribute! Source on GitHub: https://github.com/dutu/run-on-tails/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607